alter table DDCUI_MESSAGE alter column ENTITY_CAPTION rename to ENTITY_CAPTION__U98906 ^
alter table DDCUI_MESSAGE alter column ENTITY_REFERENCE_CLASS rename to ENTITY_REFERENCE_CLASS__U42171 ^
alter table DDCUI_MESSAGE alter column ENTITY_REFERENCE_ID rename to ENTITY_REFERENCE_ID__U52547 ^
